# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/lucas/.oh-my-zsh"
export TERM='xterm-256color'

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git tmux)

ZSH_TMUX_AUTOSTART="true"
ZSH_TMUX_AUTOCONNECT="false"

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Exported from Bash
clear
# === Customized aliases ===
# SSH aliases
alias rpi="ssh pi@192.168.1.111"
alias devrpi="ssh pi@192.168.1.123"
alias rrpi="ssh -R 52698:localhost:52698 pi@192.168.1.111"
alias rdevrpi="ssh -R 52698:localhost:52698 pi@192.168.1.123"
rssh(){
  ssh -R 52698:localhost:52698 $1
}
enviar(){
	scp "$1" "$2@$3:~/Documents/develop/"
}
# Directories
alias dev="cd ~/Documents/develop/"
alias arduino="cd ~/Documents/develop/arduino/"
alias projects="cd ~/Documents/develop/projects/"
alias home="cd ~/Desktop"
alias raspberry="cd ~/Documents/develop/projects/raspberry/;clear"
alias tickets="cd ~/Documents/develop/tickets/;clear"
# Python
newpy(){
	sudo cp ~/Documents/develop/projects/raspberry/templates/base.py $1.py
}
debug(){
	sudo pudb "$1"
}
# Django
alias run="clear;python manage.py runserver 0.0.0.0:8000"
# Git
alias gs="sudo git status"
alias ga="sudo git add"
alias gc="sudo git commit -m"
alias gp="sudo git push"
# Vim docker
alias python-vim='docker run -it --rm -v $(pwd):/src --workdir /src fedeg/python-vim:latest'

# Initial dir
dev

# added by Anaconda2 5.1.0 installer
export PATH="/Users/lucas/anaconda2/bin:$PATH"
export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages/

function _update_ps1()
{
    export PROMPT="$(~/Documents/develop/powerline-zsh/powerline-zsh.py $?)"
}
precmd()
{
    _update_ps1
}
# Homebrew
PATH=/bin:/usr/bin:/usr/local/bin:${PATH}
export PATH
